CREATE TYPE "public"."complaint_channel" AS ENUM('hotline','in_person','sms','email','suggestion_box','community_meeting','other');--> statement-breakpoint
CREATE TYPE "public"."complaint_category" AS ENUM('service_quality','staff_conduct','corruption_fraud','sgbv_protection','distribution_issue','eligibility_targeting','data_privacy','suggestion','other');--> statement-breakpoint
CREATE TYPE "public"."complaint_sensitivity" AS ENUM('standard','sensitive');--> statement-breakpoint
CREATE TYPE "public"."complaint_status" AS ENUM('received','under_review','investigating','resolved','closed','escalated');--> statement-breakpoint
CREATE TYPE "public"."complaint_priority" AS ENUM('low','medium','high','critical');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "complaints" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"status" "record_status" DEFAULT 'draft' NOT NULL,"created_by" uuid NOT NULL,"updated_by" uuid,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL,"is_archived" boolean DEFAULT false NOT NULL,"archived_at" timestamp with time zone,"archived_by" uuid,"notes" text,"organization_id" uuid NOT NULL,"code" text NOT NULL,"channel" "complaint_channel" NOT NULL,"category" "complaint_category" NOT NULL,"sensitivity" "complaint_sensitivity" DEFAULT 'standard' NOT NULL,"is_anonymous" boolean DEFAULT false NOT NULL,"complainant_name" text,"complainant_phone" text,"beneficiary_id" uuid,"grant_id" uuid,"description" text NOT NULL,"complaint_status" "complaint_status" DEFAULT 'received' NOT NULL,"priority" "complaint_priority" DEFAULT 'medium' NOT NULL,"received_date" timestamp with time zone DEFAULT now() NOT NULL,"due_date" timestamp with time zone,"assigned_to" uuid,"resolution_summary" text,"resolved_date" timestamp with time zone,"satisfaction_rating" integer,CONSTRAINT "complaints_code_unique" UNIQUE("code"));--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "complaint_updates" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"status" "record_status" DEFAULT 'draft' NOT NULL,"created_by" uuid NOT NULL,"updated_by" uuid,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL,"is_archived" boolean DEFAULT false NOT NULL,"archived_at" timestamp with time zone,"archived_by" uuid,"notes" text,"complaint_id" uuid NOT NULL,"organization_id" uuid NOT NULL,"update" text NOT NULL);--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "complaints" ADD CONSTRAINT "complaints_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "complaints" ADD CONSTRAINT "complaints_beneficiary_id_beneficiaries_id_fk" FOREIGN KEY ("beneficiary_id") REFERENCES "public"."beneficiaries"("id") ON DELETE no action ON UPDATE no action;EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "complaints" ADD CONSTRAINT "complaints_grant_id_grants_id_fk" FOREIGN KEY ("grant_id") REFERENCES "public"."grants"("id") ON DELETE no action ON UPDATE no action;EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "complaints" ADD CONSTRAINT "complaints_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "complaint_updates" ADD CONSTRAINT "complaint_updates_complaint_id_complaints_id_fk" FOREIGN KEY ("complaint_id") REFERENCES "public"."complaints"("id") ON DELETE no action ON UPDATE no action;EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN ALTER TABLE "complaint_updates" ADD CONSTRAINT "complaint_updates_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "complaint_org_idx" ON "complaints" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "complaint_status_idx" ON "complaints" USING btree ("complaint_status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cupdate_complaint_idx" ON "complaint_updates" USING btree ("complaint_id");
