export type UserRole =
  | "super_admin"|"admin"|"finance_manager"
  | "program_manager"|"hr_manager"
  | "procurement_officer"|"warehouse_manager"|"viewer";

export const PERMISSIONS = {
  GRANTS_VIEW:"grants:view", GRANTS_CREATE:"grants:create",
  GRANTS_EDIT:"grants:edit", GRANTS_APPROVE:"grants:approve",
  PROCUREMENT_VIEW:"procurement:view", PROCUREMENT_CREATE:"procurement:create",
  PROCUREMENT_APPROVE:"procurement:approve",
  VENDORS_VIEW:"vendors:view", VENDORS_CREATE:"vendors:create",
  VENDORS_APPROVE:"vendors:approve",
  HR_VIEW:"hr:view", HR_CREATE:"hr:create", HR_PAYROLL:"hr:payroll",
  INVENTORY_VIEW:"inventory:view", INVENTORY_MANAGE:"inventory:manage",
  ACCOUNTING_VIEW:"accounting:view", ACCOUNTING_POST:"accounting:post",
  SETTINGS_MANAGE:"settings:manage", USERS_MANAGE:"users:manage",
} as const;

export const ROLE_PERMISSIONS: Record<UserRole,string[]> = {
  super_admin: Object.values(PERMISSIONS),
  admin: [
    PERMISSIONS.GRANTS_VIEW, PERMISSIONS.GRANTS_CREATE, PERMISSIONS.GRANTS_EDIT,
    PERMISSIONS.PROCUREMENT_VIEW, PERMISSIONS.PROCUREMENT_CREATE, PERMISSIONS.PROCUREMENT_APPROVE,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.VENDORS_CREATE, PERMISSIONS.VENDORS_APPROVE,
    PERMISSIONS.HR_VIEW, PERMISSIONS.HR_CREATE,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ACCOUNTING_VIEW, PERMISSIONS.USERS_MANAGE,
  ],
  finance_manager: [
    PERMISSIONS.GRANTS_VIEW, PERMISSIONS.GRANTS_APPROVE,
    PERMISSIONS.PROCUREMENT_VIEW, PERMISSIONS.PROCUREMENT_APPROVE,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.HR_VIEW, PERMISSIONS.HR_PAYROLL,
    PERMISSIONS.ACCOUNTING_VIEW, PERMISSIONS.ACCOUNTING_POST,
  ],
  program_manager: [
    PERMISSIONS.GRANTS_VIEW, PERMISSIONS.GRANTS_CREATE, PERMISSIONS.GRANTS_EDIT,
    PERMISSIONS.PROCUREMENT_VIEW, PERMISSIONS.PROCUREMENT_CREATE,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.HR_VIEW, PERMISSIONS.INVENTORY_VIEW,
  ],
  hr_manager: [
    PERMISSIONS.HR_VIEW, PERMISSIONS.HR_CREATE, PERMISSIONS.HR_PAYROLL,
    PERMISSIONS.ACCOUNTING_VIEW,
  ],
  procurement_officer: [
    PERMISSIONS.PROCUREMENT_VIEW, PERMISSIONS.PROCUREMENT_CREATE,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.VENDORS_CREATE, PERMISSIONS.INVENTORY_VIEW,
  ],
  warehouse_manager: [
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.PROCUREMENT_VIEW,
  ],
  viewer: [
    PERMISSIONS.GRANTS_VIEW, PERMISSIONS.PROCUREMENT_VIEW, PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.HR_VIEW, PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.ACCOUNTING_VIEW,
  ],
};

export function hasPermission(role: UserRole, permission: string): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
